language: node_js
node_js:
  - 16.9.1

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - sudo apt-get update
  - sudo apt-get remove nodejs
  - nvm install 18.12.1

install:
  - yarn

test:
  except:
    - branches
script: make test
before_deploy: "echo 'ready?'"
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $AUTH_TOKEN
  on:
    branch: main
  only:
    - /^v\w*\-?\d\.\d\.\d/
  except:
    - branches
