language: node_js
node_js: '8'

cache:
  yarn: true
  directories:
    - node_modules


install:
  - yarn --frozen-lockfile --non-interactive

before_deploy: "echo 'ready?'"
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $AUTH_TOKEN
  on:
    branch: master
