language: node_js
node_js: '16.15.1'

cache:
  yarn: true
  directories:
    - node_modules


install:
  - npm install
script: npm test
after_success: npm run coverage

before_deploy:
  - "echo 'ready?'"


deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $AUTH_TOKEN
  on:
    branch: main
  only:
    - /^v\w*\-?\d\.\d\.\d/
  except:
    - branches
