language: node_js
node_js: '18.0.0'

cache:
  yarn: true
  directories:
    - node_modules


install:
  - yarn

before_deploy: "echo 'ready?'"
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $AUTH_TOKEN
  on:
    branch: main
  only:
    - /^v\w*\-?\d\.\d\.\d/
  except:
    - branches
