name: Test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
        # - name: Fetch develop branch
        # run: git fetch origin develop
        # - name: develop branch
        # run: git branch develop origin/develop
        # - name: Git diff
        # run: git diff --name-only origin/develop HEAD
      - name: 'Install Deps'
        run: npm install
      - name: 'Test'
        run: npx vitest --coverage.enabled --changed
      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v1
